# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('amount', models.FloatField()),
                ('is_paid', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Card')),
            ],
        ),
    ]
