# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='card',
            name='month',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='N\xfamero de Tarjeta'),
        ),
        migrations.AlterField(
            model_name='card',
            name='year',
            field=models.CharField(choices=[('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27')], max_length=2, verbose_name='A\xf1o'),
        ),
    ]
